apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    app: es-data
spec:
  serviceName: es-data
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: es-data
  template:
    metadata:
      labels:
        app: es-data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
        - name: es-data
          image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
          imagePullPolicy: Always
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: discovery.zen.ping.unicast.hosts
              value: "es-discovery"
          ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport
          volumeMounts:
          - name: elastic-search
            mountPath: /usr/share/elasticsearch/data
            subPath: es-data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: elastic-search
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi