apiVersion: v1
kind: Service
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  selector:
    app: elastic
  ports:
  - port: 9200
    name: http
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
spec:
  serviceName: "elastic"
  podManagementPolicy: "Parallel"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport
          volumeMounts:
          - name: elastic-search
            mountPath: /usr/share/elasticsearch/data
            subPath: es-data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: elastic-search
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi